openapi: 3.1.1
info:
  title: SPAJAM 2025 API
  description: SPAJAM 2025のAPI仕様書
  version: 1.0.0
servers:
  - url: http://127.0.0.1:54321
    description: ローカル開発環境
  - url: https://<PROJECT_REF>.supabase.co
    description: 本番環境

paths:
  # Auth関連のパス
  /auth/v1/signup:
    $ref: './paths/auth.yaml#/signup'
  /auth/v1/token:
    $ref: './paths/auth.yaml#/signin'

  # Test関連のパス
  /functions/v1/api/test/ping:
    $ref: './paths/test.yaml#/ping'
  /functions/v1/api/test/greet:
    $ref: './paths/test.yaml#/greet'
  /functions/v1/api/test/me:
    $ref: './paths/test.yaml#/me'

components:
  $ref: './components/schemas.yaml#/components'

tags:
  - name: Auth
    description: 認証関連の操作
  - name: Test
    description: テスト用エンドポイント
